### ISSUE TITLE
Second session feedback

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#10]
I just ran my second session in FoundryVTT, and I got a lot of feedback from my players in regards to the system/sheets. Overall impression were positive, but there were some gripes as well, and a bug or two cropped up. Our session was mostly focused on the Role sheets, as we did downtime between missions. I'll try to separate each thing into its own issue for better tracability, but here's the summary:

**The good:**

- The Marshal role sheet and how it integrates with all the available actors is really well made.
- The Commander's sheet also worked well.
- Everyone liked how loadout and listing of items were handled, after they got used to the interface.

**The bad/wonky:**

-  Some sheets (primarily Spymaster/Quartermaster) have a few too many tabs, where you need to flip back and forth to get the necessary information to make a roll.
- Tooltips are a bit slow to appear (will elaborate on this, not sure it can be fixed in the sheets).
- Some lists are much less concise than the Roll20 sheets (example, QM resources tab)

I'll try to make separate issues with examples and suggestions, but keep in mind that a bunch of these may range into "it doesn't look like I'm used to" territory, so I'll leave it to your discretion if you want to implement them or not.

**Comment by orkaboy** [comment]
Sorry for the spam :)

**Comment by drewg13** [comment]
Whoa, that's... extensive.  I appreciate the level of detail though and especially the PR.  Glancing over these, most are simple enough.  I was pretty sure that one would be a simple fix.
