### ISSUE TITLE
Feature request: All Items remove

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#12]
It seems that the "All Items" tab that is on most sheets is mostly intended as a debug feature. It adds a tiny bit of clutter to the sheets, so maybe it could be possible to conditionally remove the tab from all sheets it appears on in the game settings.

**Comment by drewg13** [comment]
It is mostly intended as a catch-all for fixing issues, but I can do what I did with the Effects tab and make it GM only very easily, as the GM is the one usually tasked with fixing problems anyway.  See if that works for you in the next version.
