### ISSUE TITLE
Feature request: Quartermaster project "shout"

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#13]
One of my players (the quartermaster, unsurprisingly) requested a feature for the QM projects that is present for a lot of the other "items" in the sheets, a "print" button next to each project that puts the project into chat. This would be similar to the "bell" icon on the QM sheet in Roll20.

So expected behavior is:

- Player opens up the QM sheet and jumps over to projects.
- He wants to show the others what the project status is (without necessarily changing the project in any way, if the chat log feature is on).
- He presses the new shiny speech-bubble icon next to the project name.
- A blurb appears in chat with the following info: The project name, description, the clock itself.

**Comment by drewg13** [comment]
Good suggestion, should be easy to add.

**Comment by drewg13** [comment]
Done, added to next version.  This was slightly trickier than I thought.
