### ISSUE TITLE
Visual: QM resource checkboxes

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#16]
A relatively minor visual gripe (may be a "this doesn't look like roll20" one) my players raised was that resource uses on the QM sheet (food, black shot etc) are listed as a dropdown rather than a list of checkboxes.

Visually, it would probably be easier to read at a glance the state of the Legion's coffers if resource uses were represented by x-boxes/max, similar to the way the Action ratings look. Roll20 example:

![image](https://user-images.githubusercontent.com/1805679/171057069-d14d7f8d-edfd-4593-ad6b-e79f5e1abf7b.png)

For most things, the maximum would be 3, but the food stores in particular are of course dependent on the number of Supply Carts that the Legion has (something that the current sheet already accounts for).

**Comment by drewg13** [comment]
Interesting.  I liked the dropdowns because they take up less space and found a single number easier to read than a row of boxes.  But if you're assessing the information for general "amount" rather than numerical precision, this may be preferable.  I'll think on this one.

**Comment by drewg13** [comment]
Working on this now, including the Specialist Action usage tracker dropdowns.  I'll probably leave it as an optional setting.
![image](https://user-images.githubusercontent.com/1455026/172512581-07a1b6d5-756a-4c68-85ca-4f57fc2bea00.png)

**Comment by orkaboy** [comment]
Looks pretty neat to me. Unfortunately haven't been able to have another session yet; we had another one planned but my ISP decided to suddenly put me behind a NAT, so working on trying to get around that.

**Comment by drewg13** [comment]
OK, this is complete.  Should be in next release.
Re the NAT, I've had good luck recently with the free Oracle hosting.  There's zero support, but if you're comfortable maintaining Ubuntu from a command line and make regular backups, the price is hard to beat and the control level is nearly the same as local hosting.
https://foundryvtt.wiki/en/setup/hosting/always-free-oracle

**Comment by orkaboy** [comment]
Looks interesting. I'll look into that. For now I'm trying to get a public IP with my ISP, but as it's a paid service it's not the best long term solution. I'll look into setting up a free cloud machine and migrating to it.

As for the feature itself, is this applied to actor item uses too (example, Ammo), or is that still a drop-down? I don't recall if any other places use the drop-down for uses, but keeping a consistent style is probably a good idea.
