### ISSUE TITLE
Visual: Merge QM Resources and Personnel

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#17]
In the spirit of trying to reduce extra tabs, maybe it would be better to put the Personnel in a separate heading below the Material on the resource tab. This would remove the extra tab, since mechanically there's not too much difference between the two types of resources in the game.

In general, my players preferred scrolling a little to switching between tabs. Similar to the way that Resouces has "Supply" and "Materiel" as headings, the suggestion is to add the "Non-Legion Personnel" to the same tab.

**Comment by drewg13** [comment]
This makes sense and is pretty easy to do.  I generally tried to keep things confined to a single "page".
Fixed in next version.
