### ISSUE TITLE
Feature request: QM Acquire Assets text

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#18]
Similar to the way that the Long-term Projects tab on the QM sheet has the Long-term Project Campaign action listed at the top (including the Boosted effect), it would be good if the Materiel/Non-legion Personnel entries had this information as well (for Acquire Asset).

I'm not 100% sure if this would look better always visible at the top of the tab (like the Long-term Projects one), or if it would be better if it appeared in the pop-up for Add Item.

To be specific, this is the text I'd like shown in connection to the Resources/Personnel tab:
![image](https://user-images.githubusercontent.com/1805679/171058001-438182a4-eb32-4102-bdc4-01184391dfa2.png)

This piece of information (the required quality level to get a particular asset) would also be nice to have somewhere on the QM sheet:
![image](https://user-images.githubusercontent.com/1805679/171058162-daeae428-66d6-4e5d-b1e8-cc3d3bb424c2.png)

**Comment by drewg13** [comment]
Seems reasonable.  I have no idea where that last bit came from though.  It doesn't make any sense, as it doesn't match up with the roll results.  There's no such thing as "Normal" or "Rare" quality levels that I can find.  And the information is largely covered already, so seems mostly redundant,

**Comment by orkaboy** [comment]
The second blurb is from some cheat-sheet, and uses wrong terminology. The info I was after is on page 137 in the rulebook:

> Roll the location's assets rating to determine the quality of the asset that is acquired, applying any of these special rules when you do. (1-3: Poor. 4/5: Standard. 6: Fine. Critical: Exceptional.)

...

> Laborers, Siege weapons, and alchemical concoctions are **fine** quality[...] Alchemists and Mercies are **exceptional** quality[...].

Essentially, the idea is that you need to reach a certain quality rating to get the asset (similar to how acquire assets works in Blades in the Dark).

**Comment by orkaboy** [comment]
Something I see is exactly replicated in the blurb you already have... I am dumb :P
