### ISSUE TITLE
Feature request: Spymaster sheet layout

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#19]
I'm not 100% on the best way to deal with this particular issue. The core complaint raised by my players was that there are two separate tabs for Spies (under Resources) and what the spies do (Missions).

The missions tab is needed in order to know what the spies can do, and you can also roll on Long-term Assignments here, but in order to know how many dice to roll, you need the list of your spies (both for Trained/Master and for any relevant bonuses they may have, such as Liya giving +1 to Research assignments).

There are a few ways this could be solved:

- The tabs are merged, and Spies are listed above the Assignments.
- When the "Augment Mission", or any other Assignment, is clicked, all spies appear in the popup window, including all the info that is available on the Resources tab.
- The Spies on the Resources tab are moved to the top of the sheet, so they are always visible.

The second option could even allow for "picking" a particular spy, and applying the relevant mechanical effects, though this would require additional work. I think the core issue is that one has to move between tabs to get the relevant information, when it would be better to have everything visible at the same time.

**Comment by drewg13** [comment]
I consolidated some things here and added a dropdown to signify which spy is on which mission.  There are some things I don't love about it and it's crowded, but it's more usable.  Fixed in next release.
