### ISSUE TITLE
Feature request: Heritage Traits expand

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#20]
In order to know what a particular Heritage trait does (in the instances where the sheet doesn't apply it automatically), one has to do one of two things:

- hover it for a while to get the tooltip
- click on the trait to open up a large and rather busy-looking popup (the item sheet itself)

It would be nice to have a way to expand the effect of the trait (the tooltip text) by clicking a [+] button next to it, or maybe always have it visible (though this may make this section a bit long if one has all 4 traits).

This is a visual gripe that could also be dealt with by the shorter hover delay instead.

**Comment by drewg13** [comment]
I "borrowed" the expansion code from dnd5e for this and also applied it to Abilities and Items to slim those areas down.  Fixed in next release.
