### ISSUE TITLE
Visual peeve: Marshal squad page responsive width

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#22]
A (very) minor visual gripe if you are savvy in CSS:

The squad page is currently listing two columns (which is pretty good for showing all the squads in a nice way). However, if one reduces the width of the sheet, most of the second column is cropped away. The suggestion is to change the listing to a single column if the Role sheet goes below a certain width. I'm pretty sure this is possible to do with pure CSS, but I'm not the best when it comes to styling websites.

An example of what I mean, try to drag the middle separator to adjust the size of the output window (this is bootstrap though, not sure what the styles would be in Foundry):
https://www.w3schools.com/css/tryit.asp?filename=tryresponsive_bootstrap

**Comment by drewg13** [comment]
I am not CSS savvy at all or my sheets would look far far better.  CSS is by far my weakest skill in system development.  Except maybe art.
I see what you mean, but don't have an obvious solutions to correct it.  I'll think on it.

**Comment by drewg13** [comment]
I think I handled this along with some other improvements to the way lists of items flow, let me know.  Fixed in next version.
