### ISSUE TITLE
System Settings available to players

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#25]
I'm not sure if this is feasible in the implementation, but it seems the two new options: Use dropdown on Roll dialogs and Use dropdowns for items/abilities, are only set by the game master for everyone.

It would be neat if each player could configure this according to their own preferences.

**Comment by drewg13** [comment]
Huh, I learned something new today.  The settings options are an area of the API that is less well documented, at least what I can find anyway, so it didn't even occur to me that this would be possible, but apparently it is.  Works great.  Fixed in next release.
