### ISSUE TITLE
Planning ahead and chosing abilities, vs clean sheets

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#29]
This is some feedback I've gotten from my players:

Pro: The sheets are very clean, with less clutter than the roll20 sheets.
Cons: Because you can't see all the available abilities, it's more difficult to plan ahead for what you want to take in the future.

You can see the abilities under the add menu, but you need to hover each to know what they do. Essentially, you have to have the book as reference if you want a quick overview of what your character will be able to do in the future. One of the upsides of the Powered by the Apocalypse and Forged in the Dark sheets is that you get inspiration by looking at the sheet of what your character can be/progress to, something that's lacking on the Foundry sheets (but present on the roll20 ones). This becomes even more of an issue for veteran advances (granted, not handled by the paper sheets at all).

This especially becomes an issue for the Spymaster, since the sheets are set up in such a way that you need to progress through a tree, where one network is the prerequisite of another. There's currently no way (other than looking in the book or at the paper sheets/handouts) to know how to progress in the tree, since you can only see what you can acquire right now, and not what's hidden behind other requirements.

The paper sheets and roll20 both handle this by visualizing the entire tree on the Spymaster sheet. Not sure if that is the path forward or if there's some better way.

All in all, not sure what to do about this one, since the clean layout also has it's positives (which my players liked).

**Comment by drewg13** [comment]
This one isn't going to change meaningfully either.  Again, I was specifically requested to make the system such that it would not be playable without referencing the book, so being able to look these sorts of things up in the book is absolutely expected of players.  I would expect them to get their inspiration from the book itself as well.  This argument just is not going to land at all.  

Frankly, comparisons to other sheets in general terms like this are also total non-starters.  I'm not selling a product, so I don't care at all what they do, unless there's a specific and detailed implementation that's being suggested.

**Comment by orkaboy** [comment]
That's fair, I wasn't aware of the details of your talks with Stras (I assume). It's not a big deal and I can make some reference materials for my players instead using my book.
