### ISSUE TITLE
"Annointed" Chosen ability not working

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#3]
The "Annointed" ability of each Chosen (I only tested on the Horned One) is supposed to make all favor types be selectable, but the Chosen sheet only allow one favor (favor works like a radio button, rather than a multiple-selection checkbox).

**Comment by drewg13** [comment]
This was never implemented, good catch.  I'll see what I can do to get that done.

**Comment by drewg13** [comment]
Done in 1.6.0

**Comment by orkaboy** [comment]
Had to remove and re-add the ability, but it appears to work as advertised!

**Comment by drewg13** [comment]
Yes, this is a Foundry thing.  Items that are assigned to Actors are entirely separate instances from the original Items in the world or in compendiums, so making changes to the original instance either requires a complex migration process or (much simpler) removing the old one and re-adding it.
