### ISSUE TITLE
"Duties" tab

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#30]
On the Role sheets, the Duties tab carries very little information. Possibly it could be combined with another tab to reduce the amount of tab-switching. My player suggested the QM Duties+Actions be combined for example.

I'm not sure about this one, since it would vary from Role to Role what looks cleanest. Alternatively, always have the duties rendered above the tabs (though some of them are quite a lot of lines). What do you think about this?

**Comment by drewg13** [comment]
I already find the other Role sheet tabs to be too crowded and busy for my preferences, _most especially_ on the QM sheet, so I'm going to hard disagree with your player here.  Rendering above the tabs is even worse, as this is definitely not information that needs to be referred to at all times when the sheet is open, it's intended more like an overview or reference list.  If I do anything with it, I'm inclined to remove it altogether, as it doesn't track anything or have any dynamic information at all, so is a good candidate for referring to the book or sheets.
