### ISSUE TITLE
Spymaster sheet not loading properly

### ISSUE THREAD

**Issue by mordachai** [drewg13/foundryvtt-band-of-blades#31]
sheet is loaded empty, it seems that the effect [data.type >> Override >> Spymaster] is not being created. But even adding this manually doesn't make the Spy Network work properly, I cannot add any new trait in there...

**Comment by drewg13** [comment]
I'm not seeing any issues with that.  My old Spymaster works fine, a new Spymaster created in my test world works fine, and a new Spymaster in a brand new world works fine.  Please try testing it in a new world with no modules enabled and see if you experience the same issues.

**Comment by mordachai** [comment]
working now after I disable some modules, but I dont know which one since I was just preparing the session and testig a lot of things. I'll close the issue since all seems ok. Its working with the translation, so I know that at least it was not it...
