### ISSUE TITLE
Adding new Heritages/Traits

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#33]
I looked into creating new Heritages/Traits (I want to add the optional Aldermani heritages from the book to my game), and I ran into some snags similar to how I wasn't able to add new squads. I've done the following:

- Added a new Heritage as an **Item** of type **Heritage** in my world.
- The Heritage is named **Aldermani**, and has a **Aldermani Heritage** passive effect that overrides **data.heritage** on the actor to **Aldermani**.
- The heritage appears correctly in the Heritage list on the Actor sheet. When the Heritage is selected, there is a popup text with "+/- Aldermani Heritage" on the associated token (so this part appears to work).
- Next, I added Traits (**Items** of type **Trait**) to my world, setting the **Ability Class** field to **Aldermani**. No passive effects on these (they are mostly bonus ranks to actions on character creation).

The traits do not appear under the (add) Traits menu after the Aldermani heritage is applied.

I also tried to add a new Bartan trait, setting the **Ability Class** field to **Bartan** (same as the already working traits), but the new trait fails to appear in the add traits menu.

Is there some step I am missing in creating the traits? If so, is that an issue with the traits or the heritage?

**Comment by drewg13** [comment]
Good catch.  You found a very subtle bug that took me a good while to track down.  I was inconsistent in my use of the defined item type being either `trait` or `traits` and the system didn't complain or throw an error.  The result was that only traits in the compendium would show.  I'll fix that ASAP.
