### ISSUE TITLE
Feature request: Fortune roll description

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#34]
One feature that would be nice-to-have is the (optional) ability to write a note when making a fortune roll. This could be added as a text field in the dialog that pops up.

Since fortune rolls are intended to be very general purpose, it's nice to keep track of what any individual roll is actually referring to in the chat. ie, if it was a Gather Information type roll, a squad or the Chosen performing an action, or just sheer luck to decide the outcome of something.

This is primarily for the Roll Dice icon in the left icon menu in Foundry (I don't think the sheets have other "general" fortune rolls?)

**Comment by drewg13** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/1455026/178110515-c8482877-ad5e-4785-94af-ed8c3f6cb064.png)

**Comment by drewg13** [comment]
Added in v1.8.3

**Comment by orkaboy** [comment]
Sorry for late reply, I've been away from the Internet for a while. Yes, that is exactly what I was looking for, thanks!
