### ISSUE TITLE
Rookie Character sheet continuously resets action dots to default

### ISSUE THREAD

**Issue by Darunjia** [drewg13/foundryvtt-band-of-blades#37]
When assigning the "Rookie" class to a character sheet, it keeps setting the "Maneuver", "Shoot", and "Consort" Actions to their default value of 1 dot when closing and reopening the sheet.

**Comment by drewg13** [comment]
Argh, the Active Effects just never quite do what I want them to do.  I see what you mean though.  It doesn't seem to occur with the auto-created Rookies from the Marshal's Squads tab, which is how I always created my Rookies.  So until I find a way to make this work properly, we just have to fix player-created Rookies.  Here's how:

1. Save the following as a JSON file somewhere convenient 
```json
{
  "name": "Rookie",
  "type": "class",
  "img": "systems/band-of-blades/styles/assets/icons/rookie.svg",
  "data": {
    "description": "Play a Rookie if you want to earn your stripes on the field.",
    "def_abilities": "",
    "experience_clues": "If you helped your squad by staying out of the way or surviving despite the odds.",
    "skill": "",
    "class": "",
    "logic": ""
  },
  "effects": [
    {
      "_id": "JdPttJnBqz5ibETV",
      "changes": [
        {
          "key": "data.class",
          "mode": 5,
          "value": "Rookie"
        }
      ],
      "disabled": false,
      "icon": "systems/band-of-blades/styles/assets/icons/rookie.svg",
      "label": "Rookie class",
      "origin": "Item.T8bPd5ihasoY37bg",
      "transfer": true,
      "flags": {},
      "tint": ""
    }
  ],
  "flags": {
  }
}
```
2. Create an Item on the Items tab, doesn't matter what you call it
3. Right click the new Item and choose Import Data
4. Select the file you saved
5. Delete the Class from all of your problem Rookies
6. Re-add the Rookie Class Item, either through the selection popup or by dragging the newly created Item onto the sheet

Let me know if that doesn't work for you.
