### ISSUE TITLE
Band of Blades for V10?

### ISSUE THREAD

**Issue by Lordgore30** [drewg13/foundryvtt-band-of-blades#38]
Hello drewg13many things no longer work with foundry V10 such as character creation.. is there an update planned soon? you make fantastic work, thank you
a french lover of band of blades

**Comment by drewg13** [comment]
I'm confused, did you just forget to update?  It should be ready...

**Comment by Lordgore30** [comment]
Yes it's my fault , a mistake in the update unlocking. All is right now thank you so much!
