### ISSUE TITLE
Adjust icons

### ISSUE THREAD

**Issue by WallaceMcGregor** [drewg13/foundryvtt-band-of-blades#39]
Hi

When I translate the system, there are some things that overlap others, making it impossible to use the sheet properly (for example, to add specialist skills).

![chrome_mN9XsOTa3N](https://user-images.githubusercontent.com/17795541/209094080-89c7c859-422c-431c-b9e9-f5ad958ee742.jpg)

**Comment by drewg13** [comment]
Ugh, I hate CSS.  I can play with this some to try to get some improvement, but I don't know enough to make it dynamically sized for your longer labels while still maintaining a clean look for shorter labels.  As a workaround, perhaps use some sort of abbreviation scheme?

**Comment by WallaceMcGregor** [comment]
Using abbreviations is a bit awkward 😅. Also, I would have to check all the overlapping things and abbreviate each one, depending on where they appear.

**Comment by drewg13** [comment]
I played with this a LOT and got it to a place I think works OK for both English and translated content.  Let me know if this doesn't resolve the issue.

**Comment by WallaceMcGregor** [comment]
Well, it's partly solved. Specialist Actions can now reset uses, but attributes still overlap (even in English). When adding a Playbook or a Specialist Action the experience counters are moved, but not enough to press the + button to add a Specialist Action in Spanish (or completely uncover all attributes). This is annoying but minor.

![chrome_mIpYqvjgI4](https://user-images.githubusercontent.com/17795541/224917532-99e30b8c-e4dd-4be4-974d-2c11ec9f6f94.jpg)
![chrome_pXyHIUUxvO](https://user-images.githubusercontent.com/17795541/224917577-a3a841b0-5e46-46bf-99a4-37e815bbe30d.jpg)
![chrome_ruXNkb15Ln](https://user-images.githubusercontent.com/17795541/224917618-62ce4aa5-f5a8-44c2-b992-2afe4d3c4c23.jpg)

**Comment by drewg13** [comment]
I see what you mean, I neglected to test my changes with a new Rookie, so it looks better once you add a Specialist action.  I've got some more changes incoming, test them and let me know if that fixes things.

**Comment by WallaceMcGregor** [comment]
Now it works perfect, thank you very much! 👌
