### ISSUE TITLE
Feature request: Clocks tab on Quartermaster

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#4]
As a nice-to-have, it would be good if the Quartermaster Role sheet had the ability to list/create new clock actors, so custom Long-term Projects can be tracked. As it is I'm creating custom clock actors in a separate folder to keep track of this, but it would be nice to have something similar to the Spymaster's sheet (except with the ability to create new, custom clocks).

**Comment by drewg13** [comment]
The intention was to use clock Actors for this sort of thing.  Multiple custom clocks on a sheet might be tricky to implement, but I can see where that would be useful.  I'll look into it.

**Comment by drewg13** [comment]
No, that makes sense and relating it to an existing function is a very helpful way to refer to it.  I don't think there would be technical issues, just implementation issues.  I'll think on this one.

**Comment by drewg13** [comment]
This is done in 1.7.0.  I assumed a max of 6 simultaneous projects, as doing it dynamically was overly complex and tying them to existing clocks was more hassle than it's worth.

**Comment by orkaboy** [comment]
New tab looks nice! The one thing I noticed is the chat messages. Here is what happens if I,

![image](https://user-images.githubusercontent.com/1805679/170813568-033d767a-fa46-4146-b66f-fd719c97f4bd.png)

1. Change the project clock type before having assigned it a value.
2. Update the clock of a project that I have changed the name of (but it still just says Project Clock 2, instead of the project title).

Probably these messages should reflect the project name, maybe say the total ticks (so 3/8 instead of just 3). As it is, they may as well be removed to avoid clutter in chat, because the messages are not very informative.

**Comment by drewg13** [comment]
The intent here, as with all of the chat message updates, is to acknowledge to the group as a whole that shared resources are being updated or expended, since this phase of play usually involves more explicitly collaborative decision-making and I would imagine most groups don't play with all players having Owner status on all Role sheets.  They trigger when you change a lot of things on the Role sheets to facilitate communication.  You can turn them off altogether in the System Settings, but this one in particular could probably stand to be polished up a bit.

**Comment by orkaboy** [comment]
Ah, that's neat, didn't realize that you could disable the log messages.

As another minor note, I guess Scum and Villainy was used as the base for the game system? There's a bit of a legacy artifact in the game system settings:

![image](https://user-images.githubusercontent.com/1805679/170833995-4439a6ac-6213-4a46-86ed-5379d68c32e0.png)

**Comment by drewg13** [comment]
Whoops.  S&V was my first system and, like you said, I used it as a base for this one.  That's an easy fix though.

**Comment by drewg13** [comment]
Cleaned up the log message for QM Projects to reflect more useful information and filter out NaN results and fixed setting hint text.  In next version.
