### ISSUE TITLE
Squadrons losses

### ISSUE THREAD

**Issue by pplurueda** [drewg13/foundryvtt-band-of-blades#41]
Hello

Great work you have done. Congratulations!

How can I make it so that when a squad member dies, he/she disappears from the marshal's sheet without having to delete the dead person's character sheet?

I've tried removing their squad membership from their character sheet or changing their folder, but it doesn't work.

Thanks

**Comment by drewg13** [comment]
Thanks, that's an interesting question I never considered, so there's no "official" way to do that, but there are a couple of things you could do within the existing system that might work for you right now.  One way would be to create a new Squad item called Dead or Graveyard and switch that character's squad to that on their sheet.  I won't be removed from the Marshal sheet, but it will be out of the original squad section.  Another method would be to delete the squad assignment from the character's sheet completely.  In this case, they should be removed from the Marshal sheet completely.  Note that this won't work for Specialists.  I'll have to come up with a whole additional system to properly manage this status.

**Comment by pplurueda** [comment]
Finally what I have done is to create a squad called "graveyard" which in its passive effect clears the value of the "system.squad" property.
The marshal gets a new squad but there are never any legionnaires in it.
It's a solution that works for me.
Thank you very much!

**Comment by drewg13** [comment]
Neat idea.  I just added a Deceased checkbox to character sheets under the character image that should do exactly what you need.  Let me know if that doesn't work properly.

**Comment by pplurueda** [comment]
GREAT!!
