### ISSUE TITLE
Specialist list on Marshal's sheet

### ISSUE THREAD

**Issue by pplurueda** [drewg13/foundryvtt-band-of-blades#48]
Specialists are not listed on the Marshal's sheet tab.
Changing line **1225** of [**role-sheet.html**] fixed it.
`{{#if (eq specialist.system.class specType.name)}}}`

**Comment by drewg13** [comment]
I'm not having any issues with the code as it currently stands.  All my Specialists are showing up on the sheet properly.  Can you elaborate on what you're seeing?  If I had to guess, you've translated your class names in some way that's breaking the association, but the fields being compared in that line are supposed to be language-independent.  Using the `name` property is a dead giveaway that you're not using the properties that are intended to not be translated.  When you translated the Class items, did you modify the Active Effect that assigns the `system.class` property to the Actor as well (as below)?  That's not the intended usage, you should only change the Item's `name` property.
![image](https://github.com/user-attachments/assets/8aaaf59e-7547-4a4b-bb94-31167fbc4fb8)

**Comment by drewg13** [comment]
No follow up, I have to assume you worked it out.
