### ISSUE TITLE
Specialist actions

### ISSUE THREAD

**Issue by pplurueda** [drewg13/foundryvtt-band-of-blades#49]
When you add the class to a character, the special action of that class is added to the insight group.
The image is of an scout.
![image](https://github.com/user-attachments/assets/a5eba6fb-b6ee-44de-b124-5abe041c6af9)

**Comment by drewg13** [comment]
That's where it's supposed to be.  I see nothing incorrect there, unless you're trying to point out something that you haven't articulated.  Please be very clear about what you think is the issue.

**Comment by pplurueda** [comment]
You are absolutely right.
It was my mistake.
Thank you for your speedy response!

**Comment by drewg13** [comment]
It needs to be there because it shows that it contributes to Insight resistance rolls, but adding additional specialist actions does not, so they go to a separate category.
