### ISSUE TITLE
Testing/Updating to v1.6.0

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#7]
Hi again, sorry to be a bother but I haven't really tested bleeding edge stuff with Foundry yet so there may be some procedure I'm unaware of. I saw you have updated the code and upped the game version to v1.6.0, and when I do an Update All in Foundry on the game systems tab I do indeed see that it tries (and fails) to download this. Console log:

> Error: An unexpected error occurred when downloading file https://github.com/drewg13/foundryvtt-band-of-blades/archive/v1.6.0.zip: Not Found

Did you forget to create a release (v1.5.5 still shows as the latest)? Or is there some other method I should use to download the updated module? If nothing else, this probably breaks other people trying to download the game system through Foundry currently, since the manifest points to a file which doesn't exist.

**Comment by drewg13** [comment]
You're correct, I pushed the manifest change early and got interrupted before I could finish what I needed to do.  Going out now though.
