### ISSUE TITLE
Minor tweak to roll "Push yourself" text

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#8]
The Roll Options text (very helpful!) that appears when making a roll is slightly ambiguously written.

> Push Yourself: Take 2 stress for: +1d, +1 to effect, or to take action when you're incapacitated, but you can't take a Devil's Bargain

This could be read as pushing yourself giving you both +1d **and** +1 to effect, which is not the case (unless you push yourself twice for both effects). Rules ref page 24:

> For another bonus die, you can either push yourself (take 2 stress) or you can accept a Devil's Bargain. You can't get dice from both; it's one or the other. Pushing yourself can also allow you to take +1 effect. You can push for effect and still accept a Devil's Bargain for an additional die on your roll. You can also push yourself once for effect and once for +1d.

Maybe make the text:

> **Push Yourself:** Take 2 stress for: +1d (but you can't take a Devil's Bargain) **or** +1 to effect **or** to take action when you're incapacitated. You can Push Yourself multiple times for different bonuses on the same roll

Similarily, maybe clarify on Devil's Bargain text (since you **can** accept the bargain and Push Yourself for effect):

> **Devil's Bargain:** Accept a consequence to get +1d, but you can't Push Yourself **for another +1d**

**Comment by drewg13** [comment]
The perils of trying to simplify and condense highly conditional text.  This is excellent feedback.  Corrected in next version.
